apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-anouar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-anouar
  template:
    metadata:
      labels:
        app: app-anouar
    spec:
      containers:
      - name: app-anouar
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
